; rulset 由 <指定的custom_proxy_group> <匹配 url 或 ip 的逻辑 list> 组成，后者都会通过前者指定的节点访问
; custom_proxy_group 由 <名称> <切换逻辑> <其他custom_proxy_group 或 匹配关键字节点> <url-test针对的网站, 延迟切换时间等> 组成，每个 custom_proxy_group 返回一个节点
; 所以是先有custom_proxy_group，再有 ruleset

; 自定义 ruleset
; 自定义的指定翻墙列表，最高优先级
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/wmgylc/clash_rule/main/custom_proxy.list
; 自定义的全球直连列表，最高优先级
ruleset=🎯 全球直连,https://raw.githubusercontent.com/wmgylc/clash_rule/main/custom_direct.list
; 自定义的拦截列表，最高优先级
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/wmgylc/clash_rule/main/custom_reject.list
; 原list配置了v2ray走翻墙，此处改为直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/wmgylc/clash_rule/main/direct_fork_ios_rule_script.list

; gemini test
ruleset=🌍 Gemini,https://raw.githubusercontent.com/wmgylc/clash_rule/refs/heads/main/gemini.list

; 第三方 ruleset
; 大部分域名都要通过域名规则匹配，减少一次 dns 查询耗时
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list

ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/wmgylc/clash_rule/main/jav_porn.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Proxy.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Loon/OpenAI/OpenAI.list
ruleset=♻️ 国别故障转移,https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Loon/GitHub/GitHub.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=♻️ 国别故障转移,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=🎯 全球直连,[]GEOIP,LAN,no-resolve
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=♻️ 国别故障转移,[]FINAL

; Gemini test
custom_proxy_group=🌍 Gemini`url-test`^(?=.*(->|→))(?!.*(🇺🇸|🇷🇺|🇭🇰|美国|美西|美东|俄罗斯|香港|\bUS\b|\bUSA\b|\bRU\b|\bHK\b|IPv6)).*$`http://cp.cloudflare.com/generate_204`60,,120

; 基础架构
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🛑 广告拦截`select`[]REJECT
custom_proxy_group=♻️ 国别故障转移`fallback`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🇹🇷 土耳其节点`[]🇻🇳 越南节点`[]🇷🇺 俄罗斯节点`[]🇹🇼 台湾节点`[]🇦🇺 澳大利亚节点`[]🇳🇱 荷兰节点`[]🇨🇦 加拿大节点`[]🇮🇳 印度节点`[]🌐 其他国家`[]🎯 全球直连`http://cp.cloudflare.com/generate_204`60,,120

; 国别分组
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇸🇬 新加坡节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇺🇸 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇬🇧 英国节点`url-test`(英国|Great Britain|UR)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇩🇪 德国节点`url-test`(德国|Germany|DE)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇹🇷 土耳其节点`url-test`(土耳其|Turkey|Türkiye)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇻🇳 越南节点`url-test`(越南|Vietnam)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇷🇺 俄罗斯节点`url-test`(俄罗斯|RU|ru|Russia)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇹🇼 台湾节点`url-test`(台湾|TW|tw|Taiwan|taiwan)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇦🇺 澳大利亚节点`url-test`(澳大利亚|澳洲|AU|Australia)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇳🇱 荷兰节点`url-test`(荷兰|NL|Netherlands)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇨🇦 加拿大节点`url-test`(加拿大|CA|Canada)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🇮🇳 印度节点`url-test`(印|IN|India)`http://cp.cloudflare.com/generate_204`60,,120
custom_proxy_group=🌐 其他国家`url-test`(法国|意大利|西班牙|巴西|墨西哥|阿根廷|瑞士|瑞典|挪威|丹麦|芬兰|比利时|奥地利|波兰|乌克兰|阿联酋|沙特|泰国|马来西亚|菲律宾|印度尼西亚|南非|埃及|新西兰|爱尔兰|葡萄牙|希腊|捷克|罗马尼亚|智利|秘鲁|哥伦比亚|FR|IT|ES|BR|MX|AR|CH|SE|NO|DK|FI|BE|AT|PL|UA|AE|SA|TH|MY|PH|ID|ZA|EG|NZ|IE|PT|GR|CZ|RO|CL|PE|CO)`http://cp.cloudflare.com/generate_204`60,,120

enable_rule_generator=true
overwrite_original_rules=true
